version: "3.2"
services:
  nginx:
    image: naveed125/nginx-php-fpm:latest
    restart: always
    depends_on:
      - mysql
      - api
    networks:
      - frontend
      - backend
    volumes:
      - ./python/api/tokens/:/tokens
      - ${PROJECT_ROOT}/:/var/www/html
    container_name: nginx
    ports:
      - "80:80"
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql-data:/var/lib/mysql
  api:
    build: 
      context: './python'
    networks:
      - backend
      - frontend
    volumes: ['./python/api:/app/api']
    container_name: api
    ports:
      - "5000:5000"
    restart: always
    command: gunicorn --chdir api wsgi:app --reload --timeout 1000 --bind 0.0.0.0:5000
networks:
  frontend:
  backend:
volumes:
    data: